In [7]:
import numpy as np


### Jamile Marian Polycarpo

#Como é uma entrada binária, usa-se a função sigmoid
def sigmoid(x):
  return 1 / (1+ np.exp(-x))

def derivada_sigmoid(x):
  return x*(1 - x)


class RedeNeural:
  def __init__(self, n_entradas, n_camada_oculta, n_saida, learning_rate=0.4): # inicializando numero de entrada, camada oculta e saida
    self.n_entradas = n_entradas
    self.n_camada_oculta = n_camada_oculta
    self.n_saida = n_saida
    self.learning_rate = learning_rate



#inicializando pesos e bias com valores aleatórios

    self.pesos_entrada = np.random.rand(self.n_entradas, self.n_camada_oculta)
    self.pesos_saida = np.random.rand(self.n_camada_oculta, self.n_saida)


  def feedforward(self, entradas): # função feedforward
    self.entrada_camada_oculta = np.dot(entradas, self.pesos_entrada)
    self.saida_camada_oculta = sigmoid(self.entrada_camada_oculta)
    self.entrada_camada_saida = np.dot(self.saida_camada_oculta, self.pesos_saida)
    self.saida = sigmoid(self.entrada_camada_saida)

    return self.saida

  def backpropagation(self, entradas, target):

    erro = target - self.saida # calculo do erro
    saida_delta = erro * derivada_sigmoid(self.saida)

     # calculando erros da camada oculta
    erro_oculta = saida_delta.dot(self.pesos_saida.T)
    delta_oculta = erro_oculta * derivada_sigmoid(self.saida_camada_oculta) # calculando delta da camada oculta

    #update dos pesos
    self.pesos_saida += self.learning_rate * self.saida_camada_oculta.T.dot(saida_delta)
    self.pesos_entrada += self.learning_rate * entradas.T.dot(delta_oculta)



  def treino(self, entradas, targets, epochs):

        for epoch in range(epochs):
          for i in range(len(entradas)):
            entrada_dados = np.array(entradas[i], ndmin=2)
            target_dados = np.array(targets[i], ndmin=2)

            # Feedforward
            saidas = self.feedforward(entrada_dados)

            # Backpropagation
            self.backpropagation(entrada_dados, target_dados)

            if epoch % 1000 == 0:
                error = np.mean(np.abs(entrada_dados - saidas))
                print(f"Epoch {epoch}, Error: {error}")
                print(f"Pesos Camada de entrada: \n{self.pesos_entrada}\n")
                print(f"Pesos camada oculta \n{self.pesos_saida}\n")

    # Print ultimo peso atualizado
        print(f"Ultimo peso camada entrada \n{self.pesos_entrada}\n")
        print(f"Ultimo peso camada saida: \n{self.pesos_saida}\n")

if __name__ == "__main__":
  #definindo as entradas
    entrada_xor = np.array([[0,0],[0,1],[1,0],[1,1]])
    saida_xor = np.array([[0],[1],[1],[0]])
 #criando a rede neural, com numero de entradas, saidas e camada ocultas
    rede_neural = RedeNeural(n_entradas =2, n_camada_oculta=3, n_saida =1)
  #treinando a rede neural
    rede_neural.treino(entrada_xor, saida_xor, epochs=10000)

  #testando o treino da rede neural
    for i in range(len(entrada_xor)):
        entrada_dados = np.array(entrada_xor[i], ndmin=2)
        predicao_saida = rede_neural.feedforward(entrada_dados)
        print(f"Input: {entrada_xor[i]}, Predicted Output: {predicao_saida}")



















Epoch 0, Error: 0.5732744814289827
Pesos Camada de entrada: 
[[0.76977221 0.82452931 0.99115392]
 [0.01210018 0.22319625 0.79878138]]

Pesos camada oculta 
[[0.01441952]
 [0.3495823 ]
 [0.14230107]]

Epoch 0, Error: 0.5
Pesos Camada de entrada: 
[[0.76977221 0.82452931 0.99115392]
 [0.01225023 0.22678907 0.80004898]]

Pesos camada oculta 
[[0.03535741]
 [0.37270725]
 [0.17100968]]

Epoch 0, Error: 0.5
Pesos Camada de entrada: 
[[0.77006534 0.82755586 0.99244767]
 [0.01225023 0.22678907 0.80004898]]

Pesos camada oculta 
[[0.06154968]
 [0.39934887]
 [0.19895881]]

Epoch 0, Error: 0.37544002150774447
Pesos Camada de entrada: 
[[0.76928893 0.82307301 0.99102128]
 [0.01147381 0.22230622 0.79862259]]

Pesos camada oculta 
[[0.02135337]
 [0.3559055 ]
 [0.14874215]]

Epoch 1000, Error: 0.32275812180411734
Pesos Camada de entrada: 
[[ 1.72288097 -0.08931098  4.0471061 ]
 [-0.17975745  1.44867186  3.73520959]]

Pesos camada oculta 
[[-3.09527083]
 [-2.9636345 ]
 [ 4.53432463]]

Epoch 1000, Erro